version: '3.2'
services:
  prometheus:
    image: prom/prometheus:latest
    restart: always
    container_name: prometheus
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
    - cadvisor
  cadvisor:
    image: gcr.io/google-containers/cadvisor:latest
    restart: unless-stopped
    container_name: cadvisor
    privileged: true
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /dev/disk/:/dev/disk:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    - /sys/fs/cgroup:/cgroup:rw
    depends_on:
    - redis
  redis:
    image: redis:latest
    restart: always
    container_name: redis
    ports:
    - 6379:6379
